# Generated by Django 5.1.7 on 2025-03-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_contributor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contributor",
            old_name="created_at",
            new_name="joined_on",
        ),
    ]
