# Generated by Django 5.1.7 on 2025-03-27 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_rename_created_at_contributor_joined_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributors",
                to="project.project",
            ),
        ),
    ]
