# Generated by Django 5.1.7 on 2025-03-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_contributor_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contributor",
            old_name="joined_on",
            new_name="added_on",
        ),
    ]
