# Generated by Django 5.1.7 on 2025-03-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
